import type { EventInfo, Phase } from "@/lib/contracts";

// Mock catalog. Clearly sample events: the live backend serves GET /events instead.
type Seed = Omit<EventInfo, "phase" | "seats_confirmed" | "seats_reserved" | "registrations" | "server_time"> & {
  phase: Phase;
  /** pool size the mock grows toward while registration is open */
  pool: number;
};

export const CATALOG: Seed[] = [
  {
    id: "bit-n-build-2026",
    name: "Bit N Build",
    tagline: "A 24-hour build sprint, around the world in one room.",
    description:
      "GDG On Campus CRCE's flagship hackathon. Teams of up to four build for 24 hours across web, app and AI tracks, with mentors from across Mumbai's developer community. Seats are drawn by fair drop, not by who refreshes fastest.",
    category: "hackathon",
    organizer: "GDG On Campus CRCE",
    city: "Mumbai",
    venue: "Fr. CRCE, Bandra",
    starts_at: "2026-11-15T10:00:00+05:30",
    ends_at: "2026-11-16T10:00:00+05:30",
    price_inr: 0,
    seats_total: 500,
    reservation_window_s: 300,
    phase: "REGISTRATION_OPEN",
    pool: 50_000,
  },
  {
    id: "monsoon-sessions",
    name: "Monsoon Sessions",
    tagline: "An indie night under the rain shelter.",
    description:
      "Four independent bands, one long evening, and a courtyard that smells of wet earth. Standing only. The drop is live now: people in the queue are being admitted in small batches.",
    category: "concert",
    organizer: "Courtyard Collective",
    city: "Mumbai",
    venue: "Bandra Fort Amphitheatre",
    starts_at: "2026-11-21T18:30:00+05:30",
    ends_at: "2026-11-21T23:00:00+05:30",
    price_inr: 799,
    seats_total: 300,
    reservation_window_s: 300,
    phase: "ADMITTING",
    pool: 18_400,
  },
  {
    id: "devfest-mumbai-2026",
    name: "DevFest Mumbai",
    tagline: "A day of talks on the web, Android, cloud and AI.",
    description:
      "Two tracks of talks and hands-on codelabs from Google Developer Experts and local engineers. Lunch and swag included. One entry per Google account.",
    category: "conference",
    organizer: "GDG Mumbai",
    city: "Mumbai",
    venue: "Jio World Convention Centre",
    starts_at: "2026-12-06T09:00:00+05:30",
    ends_at: "2026-12-06T18:00:00+05:30",
    price_inr: 0,
    seats_total: 1_200,
    reservation_window_s: 300,
    phase: "REGISTRATION_OPEN",
    pool: 26_000,
  },
  {
    id: "midnight-screening",
    name: "Midnight Screening",
    tagline: "A restored 35mm print, after hours.",
    description:
      "The film club's yearly midnight show: a restored classic on 35mm, introduced by the restoration team. The queue has been drawn and admission opens soon.",
    category: "film",
    organizer: "Mumbai Film Club",
    city: "Mumbai",
    venue: "Regal Cinema, Colaba",
    starts_at: "2026-11-28T23:59:00+05:30",
    ends_at: "2026-11-29T02:30:00+05:30",
    price_inr: 350,
    seats_total: 420,
    reservation_window_s: 300,
    phase: "QUEUE_READY",
    pool: 9_800,
  },
  {
    id: "courtyard-comedy",
    name: "Stand-up in the Courtyard",
    tagline: "Five comics, one mic, no front row reserved.",
    description: "An open-air stand-up night with five of the city's sharpest new comics. Every seat has been confirmed.",
    category: "comedy",
    organizer: "Open Mic Mumbai",
    city: "Pune",
    venue: "The Courtyard, Koregaon Park",
    starts_at: "2026-11-14T20:00:00+05:30",
    ends_at: "2026-11-14T22:30:00+05:30",
    price_inr: 499,
    seats_total: 250,
    reservation_window_s: 300,
    phase: "SOLD_OUT",
    pool: 7_200,
  },
  {
    id: "design-systems-workshop",
    name: "Design Systems, Hands On",
    tagline: "Build a token pipeline from Figma to code in a day.",
    description:
      "A small-group workshop on design tokens, component APIs and documentation. Laptops required. Registration has closed and positions are being drawn.",
    category: "workshop",
    organizer: "Uideas Studio",
    city: "Bengaluru",
    venue: "Bangalore International Centre",
    starts_at: "2026-12-12T10:00:00+05:30",
    ends_at: "2026-12-12T17:00:00+05:30",
    price_inr: 1_500,
    seats_total: 60,
    reservation_window_s: 300,
    phase: "REGISTRATION_CLOSED",
    pool: 2_400,
  },
  {
    id: "sahyadri-trail-run",
    name: "Sahyadri Trail Run",
    tagline: "21 km of ridge line at sunrise.",
    description: "A half-marathon trail through the Western Ghats with aid stations every 5 km. Bib numbers are allocated by fair drop.",
    category: "sports",
    organizer: "Ghats Running Club",
    city: "Lonavala",
    venue: "Rajmachi Base Camp",
    starts_at: "2027-01-10T05:30:00+05:30",
    ends_at: "2027-01-10T12:00:00+05:30",
    price_inr: 1_200,
    seats_total: 800,
    reservation_window_s: 300,
    phase: "REGISTRATION_OPEN",
    pool: 11_000,
  },
];
